name: 合并请求
about: 创建一个新的合并请求，用于开发者提交代码进行代码评审合并
title: "[工单ID] <内容描述>"
body:
  - type: markdown
    attributes:
      value: |
        ## 注意事项
        
        请在右侧选择好标签，项目选择 **服务外包「绿链碳账本」** ，指派成员给 @XiaoLFeng
        否则我将无法及时收到消息进行代码评审合并！
        
        标题请按需求完成，例如：[#1] 完成用户登陆功能
        
        ## 另外
        
        请在下方填写新功能工单的内容，方便开发者快速了解工单的内容。
        
        ---
  - type: dropdown
    id: pr-dropdown-1
    attributes:
      label: 该合并请求类型
      description: 此合并请求类型是什么，例如：新功能、修复bug、性能优化等
      options:
        - 新功能
        - 修复bug
        - 性能优化
        - 代码重构
        - 文档更新
    validations:
      required: true
  - type: textarea
    id: pr-textarea-1
    attributes:
      label: 请对此合并请求进行简要描述
      description: 请简要描述此合并请求的内容，方便其他开发者快速了解。
      placeholder: 例如：完成用户登陆功能，具体实现了用户的注册、登录、退出等，以及相关的业务逻辑。
    validations:
      required: true