logging:
  level:
    com.frontleaves.fantasticeditor: debug
    com.frontleaves.fantasticeditor.mappers: debug
baidu:
  access-key: ALTAKIhysgAUX1neDDu6H3fK9M
  secret-key: 551d33123feb4b529b7aa2c33f7e030f
  sms:
    template-id: sms-tmpl-NywLwW73955
    signature-id: sms-sign-lUwWVm82965
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fantasticeditor
    username: fantasticeditor
    password: fantasticeditor
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password: ""
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: your-email-username
    password: your-email-password-or-authorization-code
baidu:
  access-key: need_set
  secret-key: need_set
  sms:
    template-id: need_set
    signature-id: need_set