spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fantasticeditor
    username: fantasticeditor
    password: fantasticeditor
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password: ""
logging:
  level:
    com.frontleaves.fantasticeditor: info
    com.frontleaves.fantasticeditor.mappers: info