spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fantasticeditor
    username: fantasticeditor
    password: fantasticeditor
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password: ""
logging:
  level:
    com.frontleaves.fantasticeditor: debug
    com.frontleaves.fantasticeditor.mappers: debug
baidu:
  access-key: need_set
  secret-key: need_set
  sms:
    template-id: need_set
    signature-id: need_set