name: "代码规范检查"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: "代码检查"
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 规范检查
        uses: super-linter/super-linter@v6.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_JAVA: true
          VALIDATE_KOTLIN: true
          JAVA_FILE_NAME: alibaba-checkstyle.xml